/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountIcon: typeof import('./src/components/accountIcon/index.vue')['default']
    AccountModal: typeof import('./src/components/accountModal/index.vue')['default']
    CancelBtn: typeof import('./src/components/cancelBtn/index.vue')['default']
    Categoryform: typeof import('./src/components/categoryform/index.vue')['default']
    CommonModal: typeof import('./src/components/commonModal/index.vue')['default']
    ContactsList: typeof import('./src/components/contactsList/contactsList.vue')['default']
    CustomExchangeModal: typeof import('./src/components/customExchangeModal/index.vue')['default']
    DialogWarning: typeof import('./src/components/dialogWarning/index.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IndexAffirm: typeof import('./src/components/dialogWarning/indexAffirm.vue')['default']
    Message: typeof import('./src/components/dialogWarning/message.vue')['default']
    NavHeader: typeof import('./src/components/navHeader/index.vue')['default']
    NetIcon: typeof import('./src/components/netIcon/index.vue')['default']
    NetWorkCard: typeof import('./src/components/netWorkCard/index.vue')['default']
    NoData: typeof import('./src/components/noData/index.vue')['default']
    NodeWarning: typeof import('./src/components/dialogWarning/nodeWarning.vue')['default']
    PopoverView: typeof import('./src/components/popover-view/index.vue')['default']
    QrcodeModal: typeof import('./src/components/qrcodeModal/index.vue')['default']
    Resetpopup: typeof import('./src/components/resetpopup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCard: typeof import('./src/components/selectCard/index.vue')['default']
    SendSuccessModal: typeof import('./src/components/sendSuccessModal/index.vue')['default']
    SliderBottom: typeof import('./src/components/sliderBottom/index.vue')['default']
    SwitchNetwork: typeof import('./src/components/switchNetwork/index.vue')['default']
    Tip: typeof import('./src/components/tip/index.vue')['default']
    WromTransition: typeof import('./src/components/wromTransition/index.vue')['default']
  }
}
